### ISSUE TITLE
First day of month doesn’t display any courses

### ISSUE THREAD

**Issue by Raclette2K** [kb-dev/UKit#34]
On Day view on the App (in the French version), if you select any first day of a month the app will tell you there is no course for that day. 

Weirdly enough, you see theses courses in the Week view.

How to reproduce:

- Open the app
- Set the langage to French
- Find a group that has classes on first day of month (4TYB703S and 4TNV703S for instance)
- Go into day view and select the first day of the month 
- See there isn’t any courses
- Go into week view and see there are courses 
- Go on Celcat to verify and see that there is a disparity

**Comment by AamuLumi** [comment]
Hey !

Thanks for reporting the bug! :)

I'll take a look at the bug this afternoon. It must be something with the request sender and dates sent to Celcat.

Stay tuned!
