### ISSUE TITLE
Week view in English is offset by one day

### ISSUE THREAD

**Issue by Raclette2K** [kb-dev/UKit#36]
In week view in the English version, weeks starts with Sunday but it’s the Monday’s classes! 
Also there is no Saturday.  

You can see in the pictures below that the Wednesday 22nd of September in the week view has the Thursday 23rd of September classes.

![BFBCCA1B-3172-48CC-9AE5-6C96577A9371](https://user-images.githubusercontent.com/4589349/134319161-ecc36bf7-f81e-4dce-bdbf-cabc66187fa9.jpeg)

![374C55DA-FACE-451D-BB19-711AB8F3B1F5](https://user-images.githubusercontent.com/4589349/134319261-e00a24c3-c8f9-40a0-b982-5fce234b5558.jpeg)

How to reproduce this bug:

- Open app
- Set to English 
- Open any group in day view and note the day and classes 
- Open the same group in week view and compare
- Observe there is a disparity between data

**Comment by AamuLumi** [comment]
Hi,

Re-thanks for your feedback! :)

I'll take a look at this with the other issue this afternoon.

Stay tuned!
