### ISSUE TITLE
Day Schedule displaying next day 

### ISSUE THREAD

**Issue by thclmnt** [kb-dev/UKit#39]
As title mention, day view is displaying classes that should be on the next day.
<img src="https://user-images.githubusercontent.com/71180560/134765151-891b0295-844c-4b14-b413-6d4e522b2335.png" width="400">
<img src="https://user-images.githubusercontent.com/71180560/134765218-c5e18083-e45d-4763-b895-ad3146fba8d6.png" width="400">
<img src="https://user-images.githubusercontent.com/71180560/134765228-017c8ce0-0fb7-47c0-b1e0-8cff5c5c63cc.png" width="400">

**Comment by AamuLumi** [comment]
Fixed by #40
