### ISSUE TITLE
Provide release builds in GitHub releases

### ISSUE THREAD

**Issue by ZettaScript** [kb-dev/UKit#41]
It would be useful for people who don't have a Google account and who have trouble using npm, to have the .apk build available in the "releases" section of the GitHub repo.

**Comment by AamuLumi** [comment]
Hey!

Yeah, it's a good idea. We will add the next releases to the repository.

Thanks for the advice! :)

**Comment by Jack3113** [comment]
La release de la version 4.0.4 a été publiée et contient le fichier apk pour une installation direct sur Android.
