### ISSUE TITLE
Suggestion : adding the classroom number on the calendar event info when synchronized

### ISSUE THREAD

**Issue by Ternoc** [kb-dev/UKit#58]
Suggestion : when timetable is synchronized in an external calendar app, the event created in the calendar lacks the classroom number in the information.

**Comment by AamuLumi** [comment]
Hey,

This feature will be added in the next release of UKit (4.1.0).
We think about releasing the new version in the next days.

And sorry for the late answer !

Best regards,

**Comment by Ternoc** [comment]
Hello, is the ios app still being updated ? 
thanks

**Comment by AamuLumi** [comment]
It seems the app hasn't be updated from our side 🤦🏼 

We're doing this during this week. Sorry for the late update.

**Comment by AamuLumi** [comment]
Update has been approved by Apple, it should be available within 24 hours.

Android update is coming soon, we're doing some changes in administration to facilitate future updates.
