### ISSUE TITLE
Écran blanc lors du démarrage de l'application sur iOS

### ISSUE THREAD

**Issue by flayzze** [kb-dev/UKit#62]
Page blanche au lancement de l’app sur iOS 16.3

https://user-images.githubusercontent.com/103002546/215166335-20367985-fc88-4109-90c3-7689e0bc152c.MOV

**Comment by Ternoc** [comment]
pareil ici. 
et avant ça la synchronisation vers le calendrier ne marchait plus

**Comment by AamuLumi** [comment]
Je viens de faire une passe dessus, et c'est un de nos serveurs qui est actuellement hors-service pour une raison que j'ignore.
On va essayer de voir d'où ça vient dans le week-end.

**Comment by AamuLumi** [comment]
Le serveur a été redémarré, et on est en train de fixer le problème pour que ça ne se reproduise plus.

Bonne journée !
